pull_request_rules:
  - name: automatic merge on CI success if HD
    conditions:
      - status-success=ci/circleci: build
      - author=hardlydifficult
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: automatic merge on CI success if approved
    conditions:
      - status-success=ci/circleci: build
      - approved-reviews-by=hardlydifficult
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}