pull_request_rules:
  - name: merge if HD
    conditions:
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: npm"
      - "status-success=ci/circleci: testContracts"
      - author=hardlydifficult
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if Greenkeeper
    conditions:
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: npm"
      - "status-success=ci/circleci: testContracts"
      - author=greenkeeper[bot]
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if imagebot
    conditions:
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: npm"
      - "status-success=ci/circleci: testContracts"
      - author=imagebot[bot]
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if approved by HD
    conditions:
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: npm"
      - "status-success=ci/circleci: testContracts"
      - approved-reviews-by=hardlydifficult
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
