pull_request_rules:
  - name: merge if HD
    conditions:
      - "status-success=ci/circleci: build"
      - author=hardlydifficult
    actions:
      merge:
        method: squash
        strict: smart
  - name: merge if Greenkeeper
    conditions:
      - "status-success=ci/circleci: build"
      - author=greenkeeper[bot]
    actions:
      merge:
        method: squash
        strict: smart
  - name: merge if approved by HD
    conditions:
      - "status-success=ci/circleci: build"
      - approved-reviews-by=hardlydifficult
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: squash
        strict: smart
  - name: delete source branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
