pull_request_rules:
  - name: merge if HD
    conditions:
      - author=hardlydifficult
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if Greenkeeper
    conditions:
      - "status-success=greenkeeper/verify"
      - author=greenkeeper[bot]
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if imgbot
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if approved by HD
    conditions:
      - approved-reviews-by=hardlydifficult
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
