pull_request_rules:
  - name: automatic merge on CI success if HD
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - author=hardlydifficult
    actions:
      merge:
        method: squash
      delete_head_branch: {}
  - name: automatic merge on CI success if approved
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - approved-reviews-by=hardlydifficult
    actions:
      merge:
        method: squash
      delete_head_branch: {}
