language: node_js
node_js:
  - "10"
script:
  - cd library && npm i && cd ..
  - cd contracts && npm i && npm run test && cd ..
  - cd website && npm i && npm run build && cd ..
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: website/dist
  fqdn: https://ethgc.com
  project-name: ethgc.com
  on:
    branch: master