version: 2.1
jobs:
  npm:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}-{{ checksum "library/package.json" }}-{{ checksum "contracts/package.json" }}-{{ checksum "website/package.json" }}

      - run: npm i
      - run: cd library && npm i && cd ..
      - run: cd contracts && npm i && cd ..
      - run: cd website && npm i && cd ..

      - run: mkdir ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: npm run lint # includes --fix
      - run: cd contracts && npm run lint
      - run: bash .circleci/commit.sh

      - run: cd contracts && npm run compile

      - run: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              cd library && npm run deploy && cd ..
            fi

      - save_cache:
          paths:
            - node_modules
            - package-lock.json
            - library/node_modules
            - library/package-lock.json
            - contracts/node_modules
            - contracts/package-lock.json
            - website/node_modules
            - website/package-lock.json
          key: npm-{{ checksum "package.json" }}-{{ checksum "library/package.json" }}-{{ checksum "contracts/package.json" }}-{{ checksum "website/package.json" }}

      - persist_to_workspace:
          root: '..'
          paths:
            - repo

  buildWebsite:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd website && npm run build && cd ..

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/website/dist

  testContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd contracts && npm run test

  push:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: mkdir ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:  |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/deploy-ghpages.sh
              bash .circleci/deploy-artifacts.sh
              bash .circleci/pr.sh
            fi

workflows:
  build:
    jobs:
      - npm:
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
      - buildWebsite:
          requires:
            - npm
      - testContracts:
          requires:
            - npm
      - push:
          requires:
            - testContracts
            - buildWebsite
