version: 2.1
jobs:
  init: # checkout and auto-lint
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      # save checkout
      - persist_to_workspace:
          root: '..'
          paths:
            - repo

      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}

      - run: npm i

      # lint and commit any changes, which may restart the build
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: npm run lint # includes --fix
      - run: bash .circleci/commit.sh

      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v1-{{ checksum "package.json" }}

  buildContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd contracts

      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v1-{{ checksum "package.json" }}

      - run: npm run compile
      - run: cd ..

      - persist_to_workspace:
          root: '..'
          paths:
            - contracts/build

  testContracts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd contracts

      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v1-{{ checksum "package.json" }}

      - run: npm run test
      - run: npm run lint # todo add --fix and push
      - run: cd ..

  buildLibrary:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd library

      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v1-{{ checksum "package.json" }}

      - run: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              npm run deploy
            fi

      - run: cd ..

  buildWebsite:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd website

      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v1-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/website/dist

      - run: cd ..

  buildDocs:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: cd docs/website

      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v1-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/docs/website/build

      - run: cd ../..

  push:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: mkdir ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: bash .circleci/deploy-ghpages.sh
      - run: bash .circleci/deploy-artifacts.sh
      - run: bash .circleci/pr.sh

workflows:
  build:
    jobs:
      - init:
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
      - buildContracts:
          requires:
            - init
      - buildDocs:
          requires:
            - init
      - buildLibrary:
          requires:
            - init
            - buildContracts
      - testContracts:
          requires:
            - init
            - buildContracts
            - buildLibrary
      - buildWebsite:
          requires:
            - init
            - buildContracts
            - buildLibrary
      - push:
          filters:
            branches:
              only:
                - master
          requires:
            - init
            - testContracts
            - buildWebsite
            - buildDocs
            - buildLibrary
