version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}-{{ checksum "library/package.json" }}-{{ checksum "contracts/package.json" }}-{{ checksum "website/package.json" }}

            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: npm i
      - run: cd library && npm i && cd ..
      - run: cd contracts && npm i && cd ..
      - run: cd website && npm i && cd ..

      - save_cache:
          paths:
            - node_modules
            - package-lock.json
            - library/node_modules
            - library/package-lock.json
            - contracts/node_modules
            - contracts/package-lock.json
            - website/node_modules
            - website/package-lock.json
          key: v2-dependencies-{{ checksum "package.json" }}-{{ checksum "library/package.json" }}-{{ checksum "contracts/package.json" }}-{{ checksum "website/package.json" }}

  lint:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      # run tests
      - run: npm run lint # includes --fix

  rest:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - run: cd contracts && npm run compile && npm run test && npm run lint && cd ..

      # artifacts
      - run: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              cd library && npm run deploy && cd ..
              bash .circleci/deploy-artifacts.sh
            fi

      - run: cd website && npm run build && cd ..

      # deploy website
      - run: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/deploy-ghpages.sh
            fi

      # commit changes (lint and/or library updated)
      - run: |
            bash .circleci/commit.sh

workflows:
  build-deploy:
    filters:
      branches:
        ignore:
          - gh-pages
          - artifacts
    jobs:
      - build
  lint:
    filters:
      branches:
        ignore:
          - gh-pages
          - artifacts
    jobs:
      - lint
  everything-else:
    filters:
      branches:
        ignore:
          - gh-pages
          - artifacts
    jobs:
      - rest