version: 2.1
jobs:
  init: # checkout and auto-lint
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive

      # save checkout
      - persist_to_workspace:
          root: '..'
          paths:
            - repo

      - restore_cache:
          keys:
            - v6-{{ checksum "package.json" }}

      - run: npm i --production --ignore-scripts

      # lint and commit any changes, which may restart the build
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: npm run lint # includes --fix
      - run: bash .circleci/commit.sh

      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v6-{{ checksum "package.json" }}

      # build library
      - restore_cache:
          keys:
            - v6-{{ checksum "SolidityContracts/library/package.json" }}
      - run: cd SolidityContracts/library && npm i --production
      - save_cache:
          paths:
            - SolidityContracts/library/node_modules
            - SolidityContracts/library/package-lock.json
          key: v6-{{ checksum "SolidityContracts/library/package.json" }}

  buildWebsite:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - restore_cache:
          keys:
            - v6-{{ checksum "SolidityContracts/library/package.json" }}
      - restore_cache:
          keys:
            - v6-{{ checksum "website/package.json" }}
      - run: cd website && npm i --production
      - save_cache:
          paths:
            - website/node_modules
            - website/package-lock.json
          key: v6-{{ checksum "website/package.json" }}

      - run: cd website && npm run build

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/website/dist

  buildDocs:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - restore_cache:
          keys:
            - v6-{{ checksum "docs/package.json" }}
      - run: cd docs && npm i --production
      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: v6-{{ checksum "docs/package.json" }}

      - run: cd docs && npm run build

      - persist_to_workspace:
          root: '..'
          paths:
            - repo/docs/docs/.vuepress/dist

  push:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: mkdir ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: bash .circleci/deploy-ghpages.sh

workflows:
  build:
    jobs:
      - init:
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
      - buildDocs:
          requires:
            - init
      - buildWebsite:
          requires:
            - init
      - push:
          filters:
            branches:
              only:
                - master
          requires:
            - init
            - buildWebsite
            - buildDocs
