
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies--{{ checksum "library/package.json" }}-{{ checksum "contracts/package.json" }}-{{ checksum "website/package.json" }}

            # fallback to using the latest cache if no exact match is found
            #- v1-dependencies-

      - run: cd library && npm i && cd ..
      - run: cd contracts && npm i && cd ..
      - run: cd website && npm i && cd ..

      - save_cache:
          paths:
            - library/node_modules
            - contracts/node_modules
            - website/node_modules
          key: v1-dependencies--{{ checksum "library/package.json" }}-{{ checksum "contracts/package.json" }}-{{ checksum "website/package.json" }}

      # run tests!
      - run: cd contracts && npm i && npm run test && cd ..
      - run: cd website && npm i && npm run build && cd ..

  # deploy
  deployment:
    production:
      branch: master
      commands:
        - ./deploy-ghpages.sh build